Repository woowa-techcamp-2022/android-banchan-05, pull requests merged in 2022-08, with the labels that each got.

#12 [FEATURE] #2 프로젝트 기본 패키지 구성하기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/seom/banchan/BanChanApplication.kt
  app/src/main/java/com/seom/banchan/FirstFragment.kt
  app/src/main/java/com/seom/banchan/MainActivity.kt
  app/src/main/java/com/seom/banchan/SecondFragment.kt
  app/src/main/java/com/seom/banchan/data/api/response/BestMenuResponse.kt
  app/src/main/java/com/seom/banchan/data/api/response/Category.kt
  app/src/main/java/com/seom/banchan/data/api/response/Menu.kt
  app/src/main/java/com/seom/banchan/data/db/entity/CartMenuEntity.kt
  app/src/main/java/com/seom/banchan/data/repository/MenuRepositoryImpl.kt
  app/src/main/java/com/seom/banchan/data/source/CartDataSource.kt
  app/src/main/java/com/seom/banchan/data/source/MenuDataSource.kt
  app/src/main/java/com/seom/banchan/data/source/local/CartDataSourceImpl.kt
  app/src/main/java/com/seom/banchan/data/source/remote/MenuDataSourceImpl.kt
  app/src/main/java/com/seom/banchan/di/DatabaseModule.kt
  app/src/main/java/com/seom/banchan/domain/model/MenuModel.kt
  app/src/main/java/com/seom/banchan/domain/repository/MenuRepository.kt
  app/src/main/java/com/seom/banchan/domain/usecase/getMenuWithCategoriesUseCase.kt
  app/src/main/java/com/seom/banchan/ui/main/MainActivity.kt
  app/src/main/java/com/seom/banchan/ui/model/home/HomeMenuModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_main.xml
Labels: 진연주🍿, 정석준🌹, feature🔥, Review Request🔥🔥, Pair👏🏻

#14 [FEATRUE] #2 - resource 추가
  .idea/misc.xml
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_cart.xml
  app/src/main/res/drawable/ic_cart_action.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_checkbox_checked.xml
  app/src/main/res/drawable/ic_checkbox_empty.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_down.xml
  app/src/main/res/drawable/ic_grid.xml
  app/src/main/res/drawable/ic_linear.xml
  app/src/main/res/drawable/ic_reload.xml
  app/src/main/res/drawable/ic_right_arrow.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/drawable/ic_user_badge.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 진연주🍿, 정석준🌹, feature🔥, Review Request🔥🔥

#13 [FEATURE] #2 build gradle 의존성 추가
  app/build.gradle
  build.gradle
Labels: 진연주🍿, 정석준🌹, feature🔥, Review Request🔥🔥, Pair👏🏻

#15 [FEATRUE] #4 - 상단 앱바 UI 구성하기
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/seom/banchan/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/content_main.xml
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 진연주🍿, 정석준🌹, feature🔥, UI⭐️, Pair👏🏻

#16 홈 화면에 탭을 이용한 화면전환 및 기획전 리스트 UI 구성하기
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/seom/banchan/BanChanApplication.kt
  app/src/main/java/com/seom/banchan/ui/adapter/FragmentPagerAdapter.kt
  app/src/main/java/com/seom/banchan/ui/adapter/ModelRecyclerAdapter.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/ModelViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/home/BestMenuViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/home/HeaderViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/menu/SmallMenuViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/home/HomeFragment.kt
  app/src/main/java/com/seom/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/seom/banchan/ui/main/MainActivity.kt
  app/src/main/java/com/seom/banchan/ui/model/CellType.kt
  app/src/main/java/com/seom/banchan/ui/model/Model.kt
  app/src/main/java/com/seom/banchan/ui/model/home/CategoryMenuModel.kt
  app/src/main/java/com/seom/banchan/ui/model/home/HeaderMenuModel.kt
  app/src/main/java/com/seom/banchan/ui/model/home/HomeMenuModel.kt
  app/src/main/java/com/seom/banchan/util/ext/FloatExtension.kt
  app/src/main/java/com/seom/banchan/util/ext/ImageVIewExtension.kt
  app/src/main/java/com/seom/banchan/util/ext/TextViewExtension.kt
  app/src/main/java/com/seom/banchan/util/mapper/ModelViewHolderMapper.kt
  app/src/main/res/drawable/background_chip.xml
  app/src/main/res/layout/fragment_best.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_best_menu.xml
  app/src/main/res/layout/item_home_header.xml
  app/src/main/res/layout/item_menu_small.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 진연주🍿, 정석준🌹, feature🔥, Review Request🔥🔥, UI⭐️, Pair👏🏻

#17 [FEATURE] #7 - 메인화면 '기획전' Data Layer단 구성하기
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/seom/banchan/BanChanApplication.kt
  app/src/main/java/com/seom/banchan/data/api/MenuApiService.kt
  app/src/main/java/com/seom/banchan/data/api/response/Category.kt
  app/src/main/java/com/seom/banchan/data/api/response/Menu.kt
  app/src/main/java/com/seom/banchan/data/repository/MenuRepositoryImpl.kt
  app/src/main/java/com/seom/banchan/data/source/MenuDataSource.kt
  app/src/main/java/com/seom/banchan/data/source/remote/MenuDataSourceImpl.kt
  app/src/main/java/com/seom/banchan/di/CoroutineModule.kt
  app/src/main/java/com/seom/banchan/di/DataSourceModule.kt
  app/src/main/java/com/seom/banchan/di/NetworkModule.kt
  app/src/main/java/com/seom/banchan/di/RepositoryModule.kt
  app/src/main/java/com/seom/banchan/domain/model/CategoryModel.kt
  app/src/main/java/com/seom/banchan/domain/model/MenuModel.kt
  app/src/main/java/com/seom/banchan/domain/repository/MenuRepository.kt
  app/src/main/java/com/seom/banchan/domain/usecase/GetMenuWithCategoriesUseCase.kt
  app/src/main/java/com/seom/banchan/domain/usecase/getMenuWithCategoriesUseCase.kt
  app/src/main/java/com/seom/banchan/ui/adapter/ModelRecyclerAdapter.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/home/HeaderViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/home/HomeFragment.kt
  app/src/main/java/com/seom/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/seom/banchan/ui/home/best/BestViewModel.kt
  app/src/main/java/com/seom/banchan/ui/main/MainActivity.kt
  app/src/main/java/com/seom/banchan/ui/model/Model.kt
  app/src/main/java/com/seom/banchan/ui/model/home/CategoryMenuModel.kt
  app/src/main/java/com/seom/banchan/ui/model/home/HeaderMenuModel.kt
  app/src/main/java/com/seom/banchan/ui/model/home/HomeMenuModel.kt
  app/src/main/java/com/seom/banchan/util/ext/ImageVIewExtension.kt
  app/src/main/java/com/seom/banchan/util/ext/StringExtension.kt
  app/src/main/java/com/seom/banchan/util/ext/TextViewExtension.kt
  app/src/main/res/layout/item_menu_small.xml
  build.gradle
Labels: 진연주🍿, 정석준🌹, feature🔥, Pair👏🏻

#19 [FEATURE] #18 - 메인화면 '기획전 이외 탭' Data Layer단 구성하기
  app/src/main/java/com/seom/banchan/data/api/MenuApiService.kt
  app/src/main/java/com/seom/banchan/data/api/response/MenuResponse.kt
  app/src/main/java/com/seom/banchan/data/repository/MenuRepositoryImpl.kt
  app/src/main/java/com/seom/banchan/data/source/MenuDataSource.kt
  app/src/main/java/com/seom/banchan/data/source/remote/MenuDataSourceImpl.kt
  app/src/main/java/com/seom/banchan/domain/repository/MenuRepository.kt
  app/src/main/java/com/seom/banchan/domain/usecase/GetMainMenusUseCase.kt
  app/src/main/java/com/seom/banchan/domain/usecase/GetSideMenusUseCase.kt
  app/src/main/java/com/seom/banchan/domain/usecase/GetSoupMenusUseCase.kt
Labels: 정석준🌹, feature🔥, Review Request🔥🔥

#26 [FEATURE] #25 화면 전환
  app/src/main/java/com/seom/banchan/ui/base/BaseFragment.kt
  app/src/main/java/com/seom/banchan/ui/main/MainActivity.kt
  app/src/main/java/com/seom/banchan/util/navigation/FragmentNavigationController.kt
Labels: 정석준🌹, feature🔥, Review Request🔥🔥

#24 [FEATURE] #11 '메인 화면 '기획전 이외 탭' 화면 스피너 UI
  app/src/main/java/com/seom/banchan/data/api/SortCriteria.kt
  app/src/main/java/com/seom/banchan/ui/adapter/SortSpinnerAdapter.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/home/TotalViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/home/sidedish/SideDishFragment.kt
  app/src/main/java/com/seom/banchan/ui/home/soupdish/SoupDishFragment.kt
  app/src/main/java/com/seom/banchan/ui/home/soupdish/SoupDishViewModel.kt
  app/src/main/java/com/seom/banchan/ui/model/Sort.kt
  app/src/main/java/com/seom/banchan/ui/model/home/TotalMenuModel.kt
  app/src/main/res/drawable/background_dropdown.xml
  app/src/main/res/drawable/selector_spinner.xml
  app/src/main/res/layout/item_home_filter.xml
  app/src/main/res/layout/item_home_total.xml
  app/src/main/res/layout/item_spinner.xml
  app/src/main/res/layout/layout_spinner.xml
Labels: 정석준🌹, feature🔥, Review Request🔥🔥, UI⭐️

#27 [FEATURE] #8 상세 화면의 기본 UI만 구성하기(장바구니 담기 sheet 제외)
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/detail/DetailMenuViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/detail/MenuInfoViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/image/ImageListItemViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/image/ImageSliderViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/seom/banchan/ui/main/MainActivity.kt
  app/src/main/java/com/seom/banchan/ui/model/CellType.kt
  app/src/main/java/com/seom/banchan/ui/model/detail/DetailMenuModel.kt
  app/src/main/java/com/seom/banchan/ui/model/detail/MenuDetailModel.kt
  app/src/main/java/com/seom/banchan/ui/model/imageSlider/ImageSliderModel.kt
  app/src/main/java/com/seom/banchan/util/ext/ImageVIewExtension.kt
  app/src/main/java/com/seom/banchan/util/ext/LinearLayoutExtension.kt
  app/src/main/java/com/seom/banchan/util/mapper/ModelViewHolderMapper.kt
  app/src/main/res/drawable/ic_active_indicator.xml
  app/src/main/res/drawable/ic_normal_indicator.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/item_image_list.xml
  app/src/main/res/layout/item_image_slider.xml
  app/src/main/res/layout/item_menu_detail.xml
  app/src/main/res/layout/item_menu_info.xml
  app/src/main/res/layout/item_menu_small.xml
Labels: 진연주🍿, feature🔥, Review Request🔥🔥, UI⭐️, 권장📌

#36 [FEATURE] #8 '상세 화면' 하단 메뉴 개수 선택 및 버튼 UI 추가하기
  app/src/main/java/com/seom/banchan/domain/model/home/MenuModel.kt
  app/src/main/java/com/seom/banchan/ui/adapter/ModelRecyclerAdapter.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/ModelViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/detail/DetailBottomButtonViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/detail/MenuCountViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/detail/MenuInfoViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/home/BestMenuViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/home/FilterViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/home/HeaderViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/home/TotalViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/image/ImageListItemViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/image/ImageSliderViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/menu/GridMenuViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/menu/LinearMenuViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/menu/SmallMenuViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/base/BaseFragment.kt
  app/src/main/java/com/seom/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/seom/banchan/ui/detail/DetailViewModel.kt
  app/src/main/java/com/seom/banchan/ui/home/best/BestFragment.kt
  app/src/main/java/com/seom/banchan/ui/main/MainActivity.kt
  app/src/main/java/com/seom/banchan/ui/model/CellType.kt
  app/src/main/java/com/seom/banchan/ui/model/detail/DetailBottomButtonModel.kt
  app/src/main/java/com/seom/banchan/ui/model/detail/MenuCountModel.kt
  app/src/main/java/com/seom/banchan/util/listener/ModelAdapterListener.kt
  app/src/main/java/com/seom/banchan/util/mapper/ModelViewHolderMapper.kt
  app/src/main/java/com/seom/banchan/util/navigation/FragmentNavigationController.kt
  app/src/main/res/drawable/background_button.xml
  app/src/main/res/drawable/background_rounded_button.xml
  app/src/main/res/drawable/ic_minus.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/layout/item_detail_bottom_button.xml
  app/src/main/res/layout/item_detail_count.xml
Labels: 진연주🍿, feature🔥, Review Request🔥🔥, 권장📌

#37 [FEATURE] #9 장바구니 추가 비지니스 로직 구현하기
  app/build.gradle
  app/src/main/java/com/seom/banchan/data/db/BanchanDatabase.kt
  app/src/main/java/com/seom/banchan/data/db/dao/CartDao.kt
  app/src/main/java/com/seom/banchan/data/db/entity/CartMenuEntity.kt
  app/src/main/java/com/seom/banchan/data/repository/CartRepositoryImpl.kt
  app/src/main/java/com/seom/banchan/data/source/CartDataSource.kt
  app/src/main/java/com/seom/banchan/data/source/local/CartDataSourceImpl.kt
  app/src/main/java/com/seom/banchan/data/source/local/RecentlyDataSourceImpl.kt
  app/src/main/java/com/seom/banchan/di/DataSourceModule.kt
  app/src/main/java/com/seom/banchan/di/DatabaseModule.kt
  app/src/main/java/com/seom/banchan/di/RepositoryModule.kt
  app/src/main/java/com/seom/banchan/domain/model/cart/CartMenuModel.kt
  app/src/main/java/com/seom/banchan/domain/repository/CartRepository.kt
  app/src/main/java/com/seom/banchan/domain/usecase/AddMenuToCartUseCase.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/detail/DetailBottomButtonViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/detail/DetailFragment.kt
  app/src/main/java/com/seom/banchan/ui/detail/DetailViewModel.kt
  build.gradle
Labels: 진연주🍿, feature🔥, Review Request🔥🔥

#46 [FIX] #45 Database Class 이름 중복으로 인해 발생한 Conflict 문제 수정
  app/src/main/java/com/seom/banchan/data/db/BanChanDatabase.kt
  app/src/main/java/com/seom/banchan/di/DatabaseModule.kt
Labels: bug🐞, 진연주🍿, Review Request🔥🔥, refactor🔨

#49 [FIX] #44 상세화면에서 상단 indicator가 스크롤 시에 중복되어 화면에 표시되는 이슈 수정
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/detail/MenuInfoViewHolder.kt
Labels: 진연주🍿, Review Request🔥🔥, refactor🔨

#55 [FEATURE] #42 장바구니 Bottom Sheet 기본 UI 동작 구성하기 merge branch 변경
  app/src/main/java/com/seom/banchan/ui/home/HomeFragment.kt
  app/src/main/java/com/seom/banchan/ui/model/home/HomeMenuModel.kt
  app/src/main/java/com/seom/banchan/ui/view/bottomsheet/OrderBottomSheetDialog.kt
  app/src/main/java/com/seom/banchan/ui/view/bottomsheet/OrderBottomSheetViewModel.kt
  app/src/main/res/layout/fragment_order_bottom_sheet.xml
Labels: 진연주🍿, feature🔥

#52 [FEATURE] #5 장바구니 (Cart) 화면 UI 및 기능 일부 구현
  app/src/main/java/com/seom/banchan/ui/adapter/ModelRecyclerAdapter.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/cart/CartCheckViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/cart/CartMenuViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/cart/CartOrderViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/cart/CartRecentViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/order/OrderInfoViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/cart/CartFragment.kt
  app/src/main/java/com/seom/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/seom/banchan/ui/main/MainActivity.kt
  app/src/main/java/com/seom/banchan/ui/model/CellType.kt
  app/src/main/java/com/seom/banchan/ui/model/cart/CartCheckModel.kt
  app/src/main/java/com/seom/banchan/ui/model/cart/CartMenuModel.kt
  app/src/main/java/com/seom/banchan/ui/model/cart/CartOrderModel.kt
  app/src/main/java/com/seom/banchan/ui/model/cart/CartRecentModel.kt
  app/src/main/java/com/seom/banchan/ui/model/order/OrderInfoModel.kt
  app/src/main/java/com/seom/banchan/util/Constant.kt
  app/src/main/java/com/seom/banchan/util/mapper/ModelViewHolderMapper.kt
  app/src/main/res/drawable/background_button_disabled.xml
  app/src/main/res/drawable/background_count.xml
  app/src/main/res/drawable/ic_down_button.xml
  app/src/main/res/drawable/ic_up_button.xml
  app/src/main/res/drawable/selector_button.xml
  app/src/main/res/drawable/selector_checkbox.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/item_cart_check.xml
  app/src/main/res/layout/item_cart_menu.xml
  app/src/main/res/layout/item_cart_order.xml
  app/src/main/res/layout/item_cart_recent.xml
  app/src/main/res/layout/item_order_info.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: 정석준🌹, feature🔥, Review Request🔥🔥, UI⭐️

#94 [FEATURE] #93 기획전 스크롤 개선
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/home/BestMenuViewHolder.kt
  app/src/main/java/com/seom/banchan/util/ext/RecyclerVIewExtension.kt
Labels: 정석준🌹, feature🔥, Review Request🔥🔥

#98 [FIX] #85 - CellType,isBest,inCart 충돌 -> CellType으로 통일
  app/src/main/java/com/seom/banchan/domain/model/home/CategoryModel.kt
  app/src/main/java/com/seom/banchan/domain/model/home/MenuModel.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/menu/SmallMenuViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/adapter/viewholder/recent/RecentMenuViewHolder.kt
  app/src/main/java/com/seom/banchan/ui/cart/CartViewModel.kt
  app/src/main/java/com/seom/banchan/ui/home/best/BestViewModel.kt
  app/src/main/java/com/seom/banchan/ui/model/CellType.kt
  app/src/main/java/com/seom/banchan/ui/model/home/HomeMenuModel.kt
  app/src/main/java/com/seom/banchan/util/mapper/ModelViewHolderMapper.kt
  app/src/main/res/layout/item_menu_recent.xml
Labels: bug🐞, 정석준🌹, Review Request🔥🔥, refactor🔨

#113 [FEATURE] #107 화면 플로우 - 프래그먼트 스택
  app/src/main/java/com/seom/banchan/util/navigation/FragmentNavigationController.kt
Labels: 정석준🌹, feature🔥, Review Request🔥🔥

#133 [REFACTOR] #132 최근 본 상품 리스트 화면 코드 수정하기
  app/src/main/java/com/seom/banchan/ui/adapter/PagingAdapter.kt
  app/src/main/java/com/seom/banchan/ui/recent/RecentFragment.kt
  app/src/main/java/com/seom/banchan/ui/recent/RecentViewModel.kt
Labels: 진연주🍿, refactor🔨
